// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UIService is the complete Wails-bound backend surface.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../pkg/service/models.js";

export function InstallItem(itemName: string): $CancellablePromise<service$0.AcceptedOperation> {
    return $Call.ByID(1746250097, itemName).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListOptionalInstalls(): $CancellablePromise<service$0.OptionalInstallItem[]> {
    return $Call.ByID(2869388195).then(($result: any) => {
        return $$createType2($result);
    });
}

export function RemoveItem(itemName: string): $CancellablePromise<service$0.AcceptedOperation> {
    return $Call.ByID(153207584, itemName).then(($result: any) => {
        return $$createType0($result);
    });
}

export function WatchOperation(operationID: string): $CancellablePromise<void> {
    return $Call.ByID(3532195087, operationID);
}

// Private type creation functions
const $$createType0 = service$0.AcceptedOperation.createFrom;
const $$createType1 = service$0.OptionalInstallItem.createFrom;
const $$createType2 = $Create.Array($$createType1);
